spring:
  application:
    name: ecommerce-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:org.ecommerce.ecommerce_service.dto.OrderConfirmation

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.main.allow-bean-definition-overriding=true
#spring.cache.type=redis




