spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ecommerce-service
              uri: lb://ECOMMERCE-SERVICE
              predicates:
                - Path=${api.prefix}/cart/**,${api.prefix}/customer/**,${api.prefix}/orders/**,${api.prefix}/item/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=${api.prefix}/payments/**
            - id: auth-server
              uri: lb://AUTH-SERVER
              predicates:
                - Path=${api.prefix}/auth/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1

api:
  prefix: /api/v1

